name: Frontend CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install --force

            - name: Build project
              run: npm run build --if-present

            - name: Deploy to dist branch
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git checkout -B dist
                  git add .
                  git commit -m 'Deploy to dist branch' || echo "No changes to commit"
                  git push -u origin dist --force
